[package]
name = "free-space"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
argh = "0.1.13"
color-eyre = "0.6.3"
humansize = "2.1.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.136"
